// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Return from "@/components/authentification/Return";
import Problem from "@/components/Problem";
import ReduxProvider from "@/redux/Provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Return /> 
      {children}
      <Problem />
    </>
  );
}
